version: '3.8'

services:
  weather_sensor:
    build: ./sensor
    container_name: weather_station
    volumes:
      - /home/pi/smart_home/config.yaml:/usr/bin/app/config.yaml
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    environment:
      - TZ=Europe/Warsaw
    depends_on:
      - mqtt_broker
  
  dashboard:
    build: ./dashboard
    container_name: dashboard
    ports: 
      - "8501:8501"
    restart: always
    volumes:
      - /home/pi/smart_home/config.yaml:/usr/bin/app/config.yaml
    depends_on:
      - mqtt_broker

  mqtt_broker:
      image: eclipse-mosquitto:2.0
      container_name: mosquitto-broker
      restart: unless-stopped
      ports:
        - "1883:1883"
        - "9001:9001"
      volumes:
        - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
        - ./mosquitto/data:/mosquitto/data
        - ./mosquitto/log:/mosquitto/log
  
  lego_scraper:
    build: ./lego_scrapper
    container_name: lego_scrapper
    env_file:
      - .env